CREATE TABLE Login
(
	LoginID INTEGER NOT NULL,
	Password CHAR(64) NOT NULL,
	Name VARCHAR(50) NOT NULL,
	UserType TINYINT NOT NULL,
	CONSTRAINT pk_Login PRIMARY KEY (LoginID)
);

CREATE TABLE Staff
(
	StaffID INTEGER NOT NULL,
	Name VARCHAR(50) NOT NULL,
	Department VARCHAR(50) NOT NULL,
	CONSTRAINT pk_Staff PRIMARY KEY (StaffID),
	CONSTRAINT fk_StaffLogin FOREIGN KEY (StaffID) REFERENCES Login(LoginID)
);

CREATE TABLE Doctor
(
	DoctorID INTEGER NOT NULL,
	Name VARCHAR(50) NOT NULL,
	Department VARCHAR(50) NOT NULL,
	Specialty VARCHAR(50) NOT NULL,
	CONSTRAINT pk_Doctor PRIMARY KEY (DoctorID),
	CONSTRAINT fk_DoctorLogin FOREIGN KEY (DoctorID) REFERENCES Login(LoginID)
);

CREATE TABLE StaffDoctor
(
	StaffID INTEGER NOT NULL,
	DoctorID INTEGER NOT NULL,
	CONSTRAINT pk_StaffDoctor PRIMARY KEY (StaffID, DoctorID),
	CONSTRAINT fk_StaffSD FOREIGN KEY (StaffID) REFERENCES Staff(StaffID),
	CONSTRAINT fk_DoctorSD FOREIGN KEY (DoctorID) REFERENCES Doctor(DoctorID)
);

CREATE TABLE HealthCard
(
	HealthCardNo VARCHAR(12) NOT NULL,
	Name VARCHAR(50) NOT NULL,
	Address VARCHAR(255) NOT NULL,
	DOB DATETIME NOT NULL,
	CONSTRAINT pk_HealthCard PRIMARY KEY (HealthCardNo)
);

CREATE TABLE Patient
(
	PatientID INTEGER NOT NULL,
	SIN INTEGER NOT NULL,
	HealthCardNo VARCHAR(12) NOT NULL,
	HealthStatus VARCHAR(50) NOT NULL,
	Phone BIGINT NOT NULL,
	DefDoctorID INTEGER NOT NULL,
	AuditTime DATETIME NOT NULL,
	AuditByID INTEGER NOT NULL, 
	CONSTRAINT pk_Patient PRIMARY KEY (PatientID),
	CONSTRAINT fk_PatientLogin FOREIGN KEY (PatientID) REFERENCES Login(LoginID),
	CONSTRAINT fk_DoctorPatient FOREIGN KEY (DefDoctorID) REFERENCES Doctor(DoctorID),
	CONSTRAINT fk_PatientAudit FOREIGN KEY (AuditByID) REFERENCES Login(LoginID)
);

CREATE TABLE DoctorPatient
(
	PatientID INTEGER NOT NULL,
	DoctorID INTEGER NOT NULL,
	CONSTRAINT pk_DoctorPatient PRIMARY KEY (PatientID, DoctorID),
	CONSTRAINT fk_PatientPD FOREIGN KEY (PatientID) REFERENCES Patient(PatientID),
	CONSTRAINT fk_DoctorPD FOREIGN KEY (DoctorID) REFERENCES Doctor(DoctorID)
);

CREATE TABLE Appointment
(
	ApptID INTEGER NOT NULL,
	DoctorID INTEGER NOT NULL,
	PatientID INTEGER NOT NULL,
	RoomNumber VARCHAR(20),
	ApptDate DATETIME NOT NULL,
	ApptType VARCHAR(50) NOT NULL,
	AuditTime DATETIME NOT NULL,
	AuditByID INTEGER NOT NULL, 
	CONSTRAINT pk_Appointment PRIMARY KEY (ApptID, AuditTime),
	CONSTRAINT fk_PatientLogin FOREIGN KEY (PatientID) REFERENCES Login(LoginID),
	CONSTRAINT fk_DoctorPatient FOREIGN KEY (DoctorID) REFERENCES Doctor(DoctorID),
	CONSTRAINT fk_ApptAudit FOREIGN KEY (AuditByID) REFERENCES Login(LoginID)
);

CREATE TABLE Visit
(
	ApptID INTEGER NOT NULL,
	ArrivalTime DATETIME NOT NULL,
	DepartTime DATETIME,
	V_Procedure VARCHAR(100),
	Result VARCHAR(50),
	Prescription VARCHAR(MAX),
	V_Comment VARCHAR(MAX),
	AuditTime DATETIME NOT NULL,
	AuditByID INTEGER NOT NULL, 
	CONSTRAINT pk_Visit PRIMARY KEY (ApptID, AuditTime),
	CONSTRAINT fk_ApptVisit FOREIGN KEY (ApptID) REFERENCES Appointment(ApptID),
	CONSTRAINT fk_VisitAudit FOREIGN KEY (AuditByID) REFERENCES Login(LoginID)
);